{
 "title": "Métricas iniciais",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Caso de uso executado com sucesso na ultima hora ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (use_case) (increase(sales_api_use_case_success[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routes Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(sales_api_response_time_seconds_bucket{route!=\"metrics\"}[1m])) by (route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UseCase Exection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(sales_api_use_case_execution_time_seconds_bucket{}[1m])) by (use_case)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}