version: '3'

services:
  app:
    build:
      context: ./php
    container_name: adoorei-app
    volumes:
      - ../:/var/www
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  nginx:
    build:
      context: ./nginx
    container_name: adoorei-nginx
    restart: always
    tty: true
    volumes:
      - ..:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mysql:
    container_name: adoorei-mysql
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
